### ISSUE TITLE
NPCs have no encumbrance

### ISSUE THREAD

**Issue by uhu79** [DrOgres/twdu#12]
might be good to have encumbrance also calculated for NPCs - some of the weaker ones can't even carry their own rations + 1 weapon, so there is room for additional challenges

**Comment by DrOgres** [comment]
given that they don't have a strength attribute there is nothing in the system to calculate encumbrance _from_.  If tracking this becomes a priority for some reason, then the NPC would need a strength first, in which case using a PC character sheet would be more useful in general.
