### ISSUE TITLE
Feature Request: Weapon Bonus

### ISSUE THREAD

**Issue by fc85057** [DrOgres/twdu#23]
Currently, there is a nice drop down menu when rolling non-combat skills (e.g. if a player has binoculars, they can select them for a bonus when rolling scout). It would be great to have this option for weapons as well (e.g. player with rifle can select it when rolling ranged combat).

**Comment by DrOgres** [comment]
click the icon on the weapon rather than the skill when using weapons 
![image](https://github.com/DrOgres/twdu/assets/74268782/8afc6ac7-0b9a-4939-ac5d-707692a82df3)
this will put all the bonuses in the roll dialog and show damage on the chat card

**Comment by fc85057** [comment]
Very cool. Will let my players know. Thanks.
