### ISSUE TITLE
Stress Bar on Tokens are set to a maximum of 100

### ISSUE THREAD

**Issue by Tarubain** [DrOgres/twdu#25]
On the Ressources Tab the Stress Bar is set to a maximum of 100 which can't be right. The result is that the bar is useless for this high maximum and it can't be changed as a GM either:

![image](https://github.com/DrOgres/twdu/assets/119525639/b78cac47-cb47-4dcb-b1b0-1d5bc2adf6d3)

**Comment by DrOgres** [comment]
not sure why they are not editable.  I'll reduce the max to make it more reasonable in the mean time

**Comment by Tarubain** [comment]
The field is locked. Nothing can be changed there. Maybe because this values are linked to the actor and therefore you can't change it. It makes sense this way. 

Good idea to reduce the max maybe to 10 because there is basically no limit how much stress you can suffer, but there are 10 stress dices in the official dice box. So I think 10 is a good max value. :)

**Comment by Tarubain** [comment]
A little Update:
Before an update to the template.json, this was your old setting:
<img width="582" alt="image" src="https://github.com/DrOgres/twdu/assets/119525639/18bafd0f-fd06-40bb-8fd9-c714a8e6c795">

For testing purpose I changed the value in the template.json to 10 and a new created characters will have this value, but every old character stuck with the old settings, either 5 or 100, depends on the system version. So every character I created with the latest version stucks on a max of 100. I didn't figure out so far how to change this though. :(

**Comment by DrOgres** [comment]
Ok next update will have a solution: 
Max stress will initially be set to 10, as the user increases the stress if the total stress is greater than the max it will update the max to be equal to the new value +1 (making the bar a bit more dynamic and will hopefully find a range that is useful for the player/GM as play progresses.  

I will do a quick migration as well to make max stress either 10 or current +1  whichever is greater for all existing actors in a world when the update is first applied.  

this should be out over the weekend

**Comment by DrOgres** [comment]
update out now

**Comment by DrOgres** [comment]
Note you may need to update actors with large Stress maximums  this macro will set ALL your actors to max stress 10

[Uploading twdu-maxhp-sanitizer.json…]()

**Comment by Tarubain** [comment]
Awesome David! Thanks for your support. <3
