### ISSUE TITLE
[BUG] Character sheets no longer show skills.

### ISSUE THREAD

**Issue by EmoCthulhu** [DrOgres/twdu#26]
As of version 1.2.1, you can no longer roll skills for PC (i.e. type "character") as the inventory page shows on both the General tab and the Inventory tab. Creating a new character, the sheets are the same - no Skills shown, just Attributes and inventory.

**Comment by DrOgres** [comment]
fixed in 1.2.2

**Comment by DrOgres** [comment]
update released
