### ISSUE TITLE
Possible module conflict. Buttons for NPC's skill levels not showing.

### ISSUE THREAD

**Issue by EmoCthulhu** [DrOgres/twdu#27]
I missed this when I was checking if NPC sheets showed skills, sorry for the extra issue. I looked through the changelogs and it doesn't seem to be on purpose, so I assume it might the same kind of handlebar issue? You can still tell the skill level by clicking to roll and seeing how many dice are in the pool, and you can still change the skill level by clicking it, but the little toggle buttons aren't showing up. I checked the animal sheets so I don't end up sending a 3rd one... They are fine.

PS I really love how you are handling max stress now! Keep up the good work.

**Comment by DrOgres** [comment]
This one I can't duplicate this is what i have for NPC:
![image](https://github.com/DrOgres/twdu/assets/74268782/bb53e162-2301-4171-928d-70bbb1a087a2)

do you have any mods running? which browser? hosted or local? if hosted where?

**Comment by EmoCthulhu** [comment]
Native Foundry - local:
![NPC-native-foundry](https://github.com/DrOgres/twdu/assets/148644976/3d33ad13-df07-42f9-b622-5015920d2100)

Hosted on the Forge, running in Chrome (latest version):
![NPC-forge-chrome](https://github.com/DrOgres/twdu/assets/148644976/ee9e87e4-f7be-466f-824b-84afc73593c1)

I have a lot of mods, so if you can't reproduce it, I'll start the process of tracking down the offender...

**Comment by DrOgres** [comment]
yeah it has to be a mod, i tried all my browsers local and forge and not getting the issue.  if you track down which one I can look into making them play nice at some point. but it looks like you have something changing the CSS which could cause this for sure

**Comment by EmoCthulhu** [comment]
Thank goodness it's none of my own mods... When I find it I'll let you know. Might be awhile as it's update day for one of the modules I collaborate on.

**Comment by EmoCthulhu** [comment]
Found it, and great news for you :). It's one that my partner-in-crime is working on but hasn't released yet, the only reason I have it installed is because I'm testing it for him, he just said he sees the code that's doing it. So it'll play nice when released. Have a great rest of your day (hope I didn't scare you too much!).

**Comment by DrOgres** [comment]
sounds good!
