### ISSUE TITLE
Multiple critical injuries causing strange issues

### ISSUE THREAD

**Issue by fc85057** [DrOgres/twdu#28]
One of the PCs has multiple critical injuries and it's causing some strange issues. There is a very large number of negative dice for both critical injury penalty and skill dice, but the negative number of skill dice is actually being rolled.

![image](https://github.com/DrOgres/twdu/assets/44118664/8d64cbfe-4870-4099-88ca-fc051efa39a4)

**Comment by DrOgres** [comment]
can you export the character and attach the json here please?  I'll look into it  and get a fix as soon as I can

**Comment by DrOgres** [comment]
nevermind, found the bug update coming shortly

**Comment by DrOgres** [comment]
fixed in 1.2.3
