### ISSUE TITLE
Duplication of transferred player character items.

### ISSUE THREAD

**Issue by UrbanZomB** [DrOgres/twdu#31]
Found a bug that duplicates the previous added items to character sheets. Could be other sheets as well.

1. Add an (item 1) from the items tab to a (character sheet 1).
2. Transfer (item 1) to another (character sheet 2).
3. Add (item 2) from the items tab to (character sheet 1 or 2), the (item 1) is duplicated again along with (item 2).

I have tried with older characters and newly created characters, the result is the same.

Edit: forgot to list versions.
Foundry 315 - TWDU 1.2.5 - all other mods removed.

**Comment by DrOgres** [comment]
fixed in 1.2.6
