### ISSUE TITLE
V12 compatibility update 

### ISSUE THREAD

**Issue by DrOgres** [DrOgres/twdu#32]
Update for v12 and drop v10 compatability

**Comment by bmcclure0719** [comment]
This says V12 compatibility but I get an error stating "system update twdu version 1.2.6 requires older version of the foundry Virtual Tabletop software:11 or older.

**Comment by DrOgres** [comment]
The update has not been released yet.  Probably Saturday. For the moment
I'd stick with v11

**Comment by DrOgres** [comment]
added in v2.0.0
