### ISSUE TITLE
Threat Meter Change disables dragging tokens?

### ISSUE THREAD

**Issue by BBendriss** [DrOgres/twdu#33]
Not sure if this might be a module conflict, intentional feature, or bug. I could not find anything about this odd issue anywhere. However I have noticed whenever the Threat Meter changes, I can no longer mouse-drag tokens on the battlemap without having to refresh Foundry first. I can still move them via cursor arrow keys, but not by the mouse.

**Comment by DrOgres** [comment]
that is indeed odd... what version of foundry?  i'll look into it as soon as I have a moment

**Comment by BBendriss** [comment]
Hi David,

Foundry V 11 Stable (Build 315)
Walking Dead v2.0.0.

Hope that helps!

**Comment by DrOgres** [comment]
ok.  found it.  when you click the button to increase the threat level it remains active, you have to click the "Select Tokens" button to be able to select and move tokens.  so for now you will need to do that manually.  I will look into re-selecting that mode automatically but this should get you rolling again in the mean time.

**Comment by DrOgres** [comment]
fixed in 2.0.1
