### ISSUE TITLE
DragN'Drop items from one PC sheet to another 

### ISSUE THREAD

**Issue by DarioLazzari** [DrOgres/twdu#34]
Please, add the possibility to drag and drop items from one PC sheet to another.
Thank you for this module!

**Comment by DrOgres** [comment]
this functionality is already in the system. Tested i can drag all equipment from the inventory tab between actors.  Note this is restricted to GM or owner of both actors...

  if it is not working please provide me with some info:
Foundry version
System Version
confirm that no other modules are active.

thanks
-David

**Comment by DrOgres** [comment]
https://github.com/user-attachments/assets/e8ed7e00-db03-48d9-9bd5-66b7f1780b5b
