### ISSUE TITLE
Skills for NPC are not clear to read

### ISSUE THREAD

**Issue by GregorHak** [DrOgres/twdu#35]
Hey, can You consider changing the visual look on skills tab (NPC Sheet)

It is hard to say which one are Expert/Trained etc. Now skills look like this:

![obraz](https://github.com/user-attachments/assets/9d6b6b3a-2c09-4d8d-9e6e-3857483a0442)

Can you edit it to look like this?
![obraz](https://github.com/user-attachments/assets/9e4949ff-f88e-4435-93a2-b09e4a99ef23)

With the full red dot they are more visible.

**Comment by DrOgres** [comment]
it's limited by CSS but I will see what I can do

**Comment by GregorHak** [comment]
well done, thx
