### ISSUE TITLE
Health bar for animals

### ISSUE THREAD

**Issue by GregorHak** [DrOgres/twdu#36]
There is no way to show a health bar for animals tokens.

To fix this, can You consider adding HP Max for animals type actors?
![obraz](https://github.com/user-attachments/assets/401cfb14-fb2f-44be-9f3f-182880098660)

**Comment by GregorHak** [comment]
@DrOgres 
After v2.0.5 update, we can now set max hp, but all animals from premium modules (e.g [core module](https://foundryvtt.com/packages/twdu-core))  after import have set current hp and max hp to 0

**Comment by DrOgres** [comment]
Yeah, that will have to be fixed and sent to Free League. Takes a little more time, but I will get it to them asap

**Comment by GregorHak** [comment]
Also now steel you can choose: Single values - health as bar option for animal token. But this option do not work (always sets bar value to 1)

![obraz](https://github.com/user-attachments/assets/16299616-8b67-4aef-a507-d2e5a08433d8)

**Comment by DrOgres** [comment]
that had to stay in there for now.  it broke some things to remove it.  use healthMax for the current term.  Once i have some scripts for migration and have updated the premium content modules the old 'health' will go away.
