### ISSUE TITLE
Secret text is always not visible

### ISSUE THREAD

**Issue by GregorHak** [DrOgres/twdu#39]
In notes tab (Character/NPC/Haven sheet) secret text is always not visible, but should be always visible to GM and probably have reveal secret text button

![obraz](https://github.com/user-attachments/assets/95e3adbf-fd4d-4952-80d5-1c87875036e7)

![obraz](https://github.com/user-attachments/assets/e19137ce-57c8-4fe4-989c-17c4fb8f4ca7)

![obraz](https://github.com/user-attachments/assets/e86fbe6b-60d7-4322-a913-3e7c970415fe)

**Comment by DrOgres** [comment]
will be fixed in next release
