### ISSUE TITLE
[Feature request] Secret Issues for NPC and haven

### ISSUE THREAD

**Issue by GregorHak** [DrOgres/twdu#40]
Hi, can You add an option to be able to make secret issues for NPC and haven ?

My suggestion:
![obraz](https://github.com/user-attachments/assets/6aa3a9a0-5d1f-4762-892f-40d19ae5fa9b)

ad 1 : shortcut to on/off hidden status for issue, also maybe when eye is open means that player can see issue and when is closed then means that this issue is hidden from players. If idea with eye symbol is bad for You, something else must be done, so that it is clear which issue is hidden and which is not hidden for players.

ad 2 : When you edit Issue You can choose to make this issue visible/hidden for players.

**Comment by DrOgres** [comment]
this will be implemented in 3.0.0

this version of the system will require foundry v12+ just FYI

**Comment by GregorHak** [comment]
Nice work
