### ISSUE TITLE
My data will not be migrated to 3.0.0. Error message

### ISSUE THREAD

**Issue by KaiderWeise** [DrOgres/twdu#43]
After updating to 3.0.0, my data is not migrated. The console displays the following error message:
![pic1](https://github.com/user-attachments/assets/e17e99c2-c971-4210-996f-b2020e27cfb7)
![pic2](https://github.com/user-attachments/assets/e2e35f5a-16f0-4d39-b6a2-5bdf732abdf7)

**Comment by KaiderWeise** [comment]
Foundry 12.331
Walking Dead Universe RPG  System 3-0-0
Run on PC-App

**Comment by KaiderWeise** [comment]
Now I have deleted all local data and then migrated the system. That worked. Unfortunately, there is now a new problem. The weapons can no longer be clicked and triggered. The skill now says “twdu.twdu.closeCombat” (see picture). If I click on the weapon, I get an error in the console.
![pic3](https://github.com/user-attachments/assets/ab24f7bb-6404-4008-a799-6f9479de67a6)
![pic4](https://github.com/user-attachments/assets/658a667e-0d0a-45ce-b5df-ff0d9e06fca3)

**Comment by DrOgres** [comment]
this is an issue with the item not having the correct skill type in them.  you can fix this short term by editing the item from the character sheet assigning the correct skill and closing it.  

I will get a fix out asap

**Comment by DrOgres** [comment]
fixed in 3.0.1 let me know if you have any other issues
