### ISSUE TITLE
Can't import modules (Core ruleset or Starter set) on Foundry - online hosting.

### ISSUE THREAD

**Issue by ghorbey** [DrOgres/twdu#6]
Hi,

I've redeemed the Foundry code, downloaded the modules and when I click on "Import adventure" button, I get the following error:

`Cannot read properties of undefined (reading '0') [foundry.js:68326:78](url/foundry.js)
    fetch foundry.js:68326
    notify foundry.js:68223
    error foundry.js:68260
    _handleError foundry.js:3468
    dispatch foundry.js:3450
    value socket.js:532
    value socket.js:459
    emit index.mjs:136
    value manager.js:207`

View error [here](https://imgur.com/a/Jg64smi).
I've tested without any other module installed, with other modules installed, in English and in French, same error each time.

Environment: Molten Hosting. (Plenty of available disk space)
Please note that on my local Foundry installation, it works fine.

I can make some testing on Molten hosting is needed.

Thanks for looking into it.

**Comment by DrOgres** [comment]
I cannot reproduce the error on my testing set up but I don't have access to Molten.  Can you confirm that other adventure compendiums will import?  

also helpful if you can provide your version of foundry 

thanks!

**Comment by ghorbey** [comment]
Hi,

It's Foundry version 11 stable build 315.

I can set you an GM access on Molten Hosting for testing, you can email me at s.paquay@gmail.com if it could help.

I've tested with Forbidden Lands Core Rules and I've got the same error but it's surely the same import code as it's also a Free League game.
Do you have any other similar module that I can test?

Thanks
